### ISSUE TITLE
How to get filepond file object id from the "open" API?

### ISSUE THREAD

**Issue by DezChuang** [pqina/filepond-plugin-image-edit#12]
Hi, Pqina.

I'm trying to integrate Filepond with [Cropper.js](https://github.com/fengyuanchen/cropperjs).

Refer to the [document](https://pqina.nl/filepond/docs/patterns/plugins/image-edit/#integrating-other-editors), I found that there is no way to get the **filepond file object id** from the **open** API so that I cannot know which image file I'm editing.

Is there any advice, thanks!

<img width="867" alt="screenshot" src="https://user-images.githubusercontent.com/21002750/83393739-defda280-a429-11ea-977e-46f62cad3e74.png">

**Comment by rikschennink** [comment]
See: https://github.com/pqina/filepond-plugin-image-edit/issues/1

And: https://github.com/pqina/filepond-plugin-image-edit/issues/11#issuecomment-627857343
