### ISSUE TITLE
How use onconfirm

### ISSUE THREAD

**Issue by hmz22** [pqina/filepond-plugin-image-edit#3]
Hi dear.
Please tell me how can call onconfirm imageEditEditor in button onClick.
I work with React and Create cropperjs editor but when submit button don’t fire onconfirm imageEditEditor
Please Help me I posted in GitHub but they deleted it.

I attached my Editor
[imageEditors.zip](https://github.com/pqina/filepond-plugin-image-edit/files/3329202/imageEditors.zip)

**Comment by rikschennink** [comment]
Hi, no double posting, I've deleted your comment in the other thread.

The post is badly formatted so it's very difficult to tell what and where the exact problem lies.

**The more effort you put in describing the issue the easier it is for other developers to help out**

**Comment by rikschennink** [comment]
You probably have to create a reference to the `onconfirm` callback in your component scope, then you can access the reference in your `onClick` handler.

**Comment by rikschennink** [comment]
Linking onconfirm and FilePond in React 👉 https://codesandbox.io/s/serene-wiles-p0j7j

**Comment by awaisali3405** [comment]
can you example for core javascript how can i use onconfirm callback after clicking done?
