### ISSUE TITLE
      editor.outputFile = false;

### ISSUE THREAD

**Issue by LoikMaksim** [pqina/filepond-plugin-image-edit#4]
```
// set default FilePond options and add bridge once
      if (!editor.filepondCallbackBridge) {
        editor.outputData = true;
        editor.outputFile = false;
```

I found that outputFile is disabled. But I need to store the original and the edited picture separately.
When i use doka i laways get null with this option in onConfirm because Doka  takes it as a parameter.

Is it mistake? Or i need in onConfirm method get File?

**Comment by rikschennink** [comment]
Hi! If you use Doka with FilePond the image transforms are handled by FilePond (as they only have to be done before upload). You can configure the FilePond image transform plugin to upload multiple file variations.

This article shows how to generate multiple variations:
https://dev.to/pqina/generating-image-thumbnails-in-the-browser-using-javascript-and-filepond-10b8

Use the `imageTransformVariantsIncludeOriginal` property to also submit the original image.

**Comment by LoikMaksim** [comment]
But its not the same.

Filepond Editor use Doka.
User edit in Doka image - and Doka  return to Filepond in process method

For example process post to server 
`user_avatar: {"crop":{"center":{"x":0.5,"y":0.5},"flip":{"horizontal":false,"vertical":false},"rotation":0,"zoom":1,"aspectRatio":null},"color":null,"output":{"type":null,"quality":null,"client":["crop","resize","filter","markup","output"]}}`
`user_avatar: (binary)` here is only image with resize / crop plugin Filepond
`user_id: 831`


Looks good, but binary file (image) - has only crop/resize transform.
When user change color- i had only json.


My server side is based on php.
I had use Doka php class.The same problem - there is only crop/resize transformation.

if change in source code (filepond-plugin-image-edit)     editor.outputFile = true;
I had edited file from Doka.

![image](https://user-images.githubusercontent.com/3988717/63160666-fac4c300-c026-11e9-9a21-151ddb8edb10.png)

**Comment by LoikMaksim** [comment]
![image](https://user-images.githubusercontent.com/3988717/63160904-922a1600-c027-11e9-8225-5d9395e584b1.png)

![image](https://user-images.githubusercontent.com/3988717/63160989-bd146a00-c027-11e9-9f11-072a77536cbf.png)


Edited in Doka image and sended to server side

on server side 
![image](https://user-images.githubusercontent.com/3988717/63160953-a837d680-c027-11e9-9177-734540a60738.png)

**Comment by rikschennink** [comment]
Do you have the latest version of all plugins and FilePond?

**Comment by LoikMaksim** [comment]
```
"filepond": "^4.4.11",
    "filepond-plugin-file-validate-type": "^1.2.4",
    "filepond-plugin-image-preview": "^4.3.2",
    "filepond-plugin-image-edit": "^1.4.0",
    "filepond-plugin-image-crop": "^2.0.3",
    "filepond-plugin-image-resize": "^2.0.4",
    "filepond-plugin-image-transform": "^3.4.3",
    "filepond-plugin-image-exif-orientation": "^1.0.6",
```
almost

**Comment by LoikMaksim** [comment]
I cannot understand why you are redefining settings Doka.
Doka docs

![image](https://user-images.githubusercontent.com/3988717/63162297-d10d9b00-c02a-11e9-83ce-82f9234114e9.png)

**Comment by LoikMaksim** [comment]
and Doka version 4.3.1 maybe i need fresh release?

**Comment by rikschennink** [comment]
Because FilePond handles the transform when used together, it’s faster because otherwise each confirmed edit would result in a new file.

Yes, please update to 5.0 and update all plugins and FilePond to their latest versions.

FYI It is correct that Doka PHP currently does not support color transforms and annotations.

**Comment by LoikMaksim** [comment]
ok tnx - i ll try.
I understand with php, that's why I want the picture to be generated on the client side.

**Comment by rikschennink** [comment]
closed because inactive.
